name: mink
version: 1

dependencies:
  - base
  - network
  - bytestring
  - transformers
  - mtl
  - split

executable:
  main: Main.hs
  source-dirs:
    - src
  ghc-options:
    - -threaded
    - -Wall
    - -Wcompat
    - -Widentities
    - -Wincomplete-record-updates
    - -Wincomplete-uni-patterns
    - -Wmissing-export-lists
    - -Wmissing-home-modules
    - -Wpartial-fields
    - -Wredundant-constraints
  extra-libraries:
    - newt
